version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'npm deps'
      prefix-development: 'npm devdeps'
      include: 'scope'
